### ISSUE TITLE
JS Code block execution bug

### ISSUE THREAD

**Issue by WickedInvi** [AutomaApp/automa#1318] opened 2023-08-13 06:58 UTC
**Describe the bug**
This code was working fine yesterday, but does not work today after the latest update.
```js
const artistsSheet = automaRefData('googleSheets', 'ArtistNames')

let artistsArray = []

for (const artist of artistsSheet) {
  if (artist.Scraped !== "Yes") {
    artistsArray.push(artist.Name)
  }
}

automaSetVariable('artistsArray', artistsArray)

automaNextBlock()
```

**To Reproduce**

1. Add JS Code block
2. Add automaRefData
3. Add automaSetVariable

**Expected behavior**
Expected artistsArray variable to be set to artistsArray array

**Desktop (please complete the following information):**
 - OS: Windows 11 - 10.0.22621 Build 22621
 - Browser: Google Chrome Version 115.0.5790.171 (Official Build) (64-bit)
 - Extension Version: 1.28.3

**Additional context**
Update - This code works
```js
automaSetVariable('artistsArray', 'Hello World')

automaNextBlock()
```
This also works
```js
// Something here

automaSetVariable('artistsArray', 'Hello World')

automaNextBlock()
```
THIS DOES NOT
```js
// const artistsSheet = automaRefData('googleSheets', 'ArtistNames')

automaSetVariable('artistsArray', 'Hello World')

automaNextBlock()
````

**Comment by NguyenCongVN** [comment] 2023-08-13 07:16
The same problem here! Using the release v1.28.2 doesn't work too.

**Comment by Kholid060** [comment] 2023-08-13 07:17
Fixed in V1.28.4

**Comment by NguyenCongVN** [comment] 2023-08-13 07:24
![image](https://github.com/AutomaApp/automa/assets/47655418/77147e5f-470e-4805-9f92-c17a784342fe)

const googleData = automaRefData('loopData', 'googleData')

const data = googleData.data

const Title = data[1]

const LocalLink = 'http://127.0.0.1:5000/files/' + data[2]

automaSetVariable('Title', Title)
automaSetVariable('LocalLink', LocalLink)

@Kholid060 My script is working a few hours ago but now this line is not working
const googleData = automaRefData('loopData', 'googleData')

It seems that there's a problem in automaRefData function

I'm using v1.28.4

**Comment by Kholid060** [comment] 2023-08-13 08:24
Is there any error on the workflow log?

**Comment by NguyenCongVN** [comment] 2023-08-13 08:37
> Is there any error on the workflow log?

The javascript line is not log any error but every lines of code after "automaRefData" line is not executed.
I think automaRefData function has a problem with loopData use-case. The other use-case seems work well

**Comment by Kholid060** [comment] 2023-08-13 09:08
> > Is there any error on the workflow log?
> 
> The javascript line is not log any error but every lines of code after "automaRefData" line is not executed. I think automaRefData function has a problem with loopData use-case. The other use-case seems work well

Do you have a workflow sample that I can use to reproduce your issue? Because I have tried to reproduce it myself, but everything is working correctly.

**Comment by ishigamii** [comment] 2023-08-13 10:52
I am having the same trouble since this morning (so the new version) as a simple code taking the global var to a variable using `automaSetVariable` gives me now the error 

```
TypeError: Cannot set properties of undefined (setting 'urls')
    at automaSetVariable (<anonymous>:37:31)
```

The code: 
![image](https://github.com/AutomaApp/automa/assets/26909067/65fa999c-3d3c-46e0-a194-ba825d0fce53)

**Comment by WickedInvi** [comment] 2023-08-13 11:03
Downloaded https://github.com/AutomaApp/automa/releases/tag/v1.28.4
Installed and imported workflow. Still getting error `Cannot set properties of undefined (setting 'artistsArray')`

**Comment by Kholid060** [comment] 2023-08-13 11:24
> Downloaded https://github.com/AutomaApp/automa/releases/tag/v1.28.4 Installed and imported workflow. Still getting error `Cannot set properties of undefined (setting 'artistsArray')`
> 
> https://www.loom.com/share/f7692aa9bf884213bdfde43d2fa13f3c

Thank you for the video, and I've found the bug. In the meantime, until the fix is published, you can change the execution context of the Javascript block into "Active Tab"

> Also getting this when I added 1.28.4

It's expected

**Closed** 2023-08-16 06:21 UTC
